# Generated by Django 3.2.5 on 2021-09-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataio',
            name='col_3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
