# Generated by Django 2.2.5 on 2021-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_imageio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageio',
            name='col_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='imageio',
            name='col_2',
            field=models.CharField(max_length=150),
        ),
    ]
