
jupyterlab:
  build: ./jupyterlab
  ports:
    - "9003:9003"
  volumes:
    - ./data:/opt/app/data
  entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=9003 --no-browser --notebook-dir=/opt/app/data --allow-root'
