# Generated by Django 2.2.5 on 2021-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210920_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIO',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('col_1', models.ImageField(upload_to='')),
                ('col_2', models.ImageField(upload_to='')),
            ],
        ),
    ]
