# Generated by Django 3.2.5 on 2021-09-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.FloatField()),
                ('col_2', models.FloatField()),
                ('col_4', models.FloatField()),
            ],
        ),
    ]
