FROM tensorflow/tensorflow:2.3.0-gpu-jupyter 
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN apt -y update
RUN apt -y upgrade
RUN apt -y install libgl1-mesa-glx
COPY . /code/