# Generated by Django 3.2.8 on 2021-10-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIO',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('col_1', models.FloatField()),
                ('col_2', models.FloatField()),
                ('col_3', models.FloatField()),
                ('col_4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageIO',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('col_1', models.CharField(max_length=150)),
                ('col_2', models.CharField(max_length=150)),
            ],
        ),
    ]
