version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - /home/hasib/db:/var/lib/postgresql/data
    environment:
      #- POSTGRES_HOST=0.0.0.0
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    #networks:
    #  - web
  web:
    container_name: web
    build: ./docker_web
    command: python manage.py runserver 0.0.0.0:9002
    volumes:
      - .:/code
      - /mnt/d:/data
    ports:
      - "9002:9002"
      - "9005:9005"
    depends_on:
      - db
    #networks:
    #  - web
      
  sever:
    container_name: server
    build: ./docker_jupyter
    command: jupyter lab --ip=0.0.0.0 --port 9003 --allow-root --no-browser --notebook-dir=/src
    volumes:
      #- .:/src
      - /mnt/e/Inference-App:/src
      - /mnt/d:/data
    ports:
      - "9003:9003"
    #networks:
    #  - web
      
#networks:
#    web: